export function exportPNG(cityData, renderer, scene, camera, postfx, overlays, timeline) {
    // Hide UI. #ui2 hosts search/legend/tour (see index.html) - without it a
    // postcard would ship with the search box or a tour card baked in.
    const ui = document.getElementById('ui');
    const ui2 = document.getElementById('ui2');
    const uiWasHidden = ui.classList.contains('hidden');
    if (!uiWasHidden) {
        ui.classList.add('hidden');
        if (ui2) ui2.classList.add('hidden');
    }

    // Force a render
    postfx.render();
    
    const webglCanvas = renderer.domElement;
    
    // Create 2D canvas to compose the final image
    const finalCanvas = document.createElement('canvas');
    const ctx = finalCanvas.getContext('2d');
    
    // Dimensions
    const w = webglCanvas.width;
    const h = webglCanvas.height;
    
    // Caption strip height
    const stripH = Math.max(60, Math.floor(h * 0.05));
    finalCanvas.width = w;
    finalCanvas.height = h + stripH;
    
    // Draw WebGL canvas
    ctx.drawImage(webglCanvas, 0, 0);
    
    // Draw caption strip
    ctx.fillStyle = '#0f0f0f';
    ctx.fillRect(0, h, w, stripH);
    
    ctx.fillStyle = '#ffffff';
    ctx.font = `${Math.floor(stripH * 0.4)}px monospace`;
    ctx.textAlign = 'left';
    ctx.textBaseline = 'middle';
    
    // Gather stats
    const repo = cityData.repo ? cityData.repo.name : 'repo';
    const numFiles = cityData.buildings.length;
    let loc = 0;
    for (const b of cityData.buildings) loc += (b.loc || 0);
    const numAuthors = cityData.git ? cityData.git.authors.length : 0;
    
    // Active mode
    const MODES = {
        1: 'Language', 2: 'Health', 3: 'Recency', 
        4: 'Ownership', 5: 'Bus factor', 6: 'Complexity'
    };
    const modeName = MODES[overlays.activeMode] || 'Language';
    
    // Date
    let dateStr = '';
    if (timeline && timeline.count > 0 && timeline.labels) {
        const lbl = timeline.labels[timeline.index];
        if (lbl) dateStr = ` · ${lbl}`;
    }
    
    const text = `${repo} · ${numFiles.toLocaleString()} files · ${loc.toLocaleString()} LOC · ${numAuthors} authors · Mode: ${modeName}${dateStr} · generated by Chronopolis`;
    
    // Padding
    const px = Math.floor(w * 0.02);
    ctx.fillText(text, px, h + stripH / 2);
    
    // Download
    const dataUrl = finalCanvas.toDataURL('image/png');
    const a = document.createElement('a');
    
    // yyyymmdd
    const today = new Date();
    const yyyymmdd = today.toISOString().split('T')[0].replace(/-/g, '');
    
    a.download = `chronopolis-${repo.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-${modeName.toLowerCase().replace(' ', '')}-${yyyymmdd}.png`;
    a.href = dataUrl;
    a.click();
    
    // Restore UI
    if (!uiWasHidden) {
        ui.classList.remove('hidden');
        if (ui2) ui2.classList.remove('hidden');
    }
}
